### ISSUE TITLE
clean up unsued/obsolete branches

### ISSUE THREAD

**Issue by pietrushnic** [pcengines/coreboot#129]

**Comment by miczyg1** [comment]
@pietrushnic I have cleaned up almost every unused branch which was created by us.

**Comment by pietrushnic** [comment]
@miczyg1 thank you. Now things look a little bit better, but 28 branches are quite a lot.

**Comment by miczyg1** [comment]
@pietrushnic tell me please whether any of these are still useful for You and should be kept:
- coreboot-4.7.x-uefi 
- coreboot-4.6.x-uefi
- apu2-uefi-new

**Comment by pietrushnic** [comment]
@miczyg1 `coreboot-4.7.x-uefi` is probably only useful branch to me.

**Comment by miczyg1** [comment]
I have further reduced the number of branches to 12. One or two have PRs open. I left some with old research in case we would like to come back to it.
