### ISSUE TITLE
Reboot cause AGESA assert

### ISSUE THREAD

**Issue by pietrushnic** [pcengines/coreboot#13]
```
ASSERTION ERROR: file 'src/northbridge/amd/pi/agesawrapper.c', line 305
```

**Comment by pietrushnic** [comment]
@miczyg1 there was thread recently about that on mailing list `AMD Family 15h and 16h: ASSERTION ERROR` - I believe information there may be useful.

**Comment by miczyg1** [comment]
The ASSERT will be present and can not be fixed due to AGESA bug:
https://review.coreboot.org/c/coreboot/+/30475

Incorrect status field set to TRUE instead of AGESA_SUCCESS will cause the return value to be AGESA_UNSUPPORTED.
