### ISSUE TITLE
make sure that sortbootorder is pulled according to release

### ISSUE THREAD

**Issue by pietrushnic** [pcengines/coreboot#14]

**Comment by miczyg1** [comment]
Each tagged release has sortbootorder's version defined in its Makefile:
https://github.com/pcengines/coreboot/blob/coreboot-4.0.x/payloads/external/sortbootorder/Makefile.inc#L1
https://github.com/pcengines/coreboot/blob/develop/payloads/external/sortbootorder/Makefile#L1
