### ISSUE TITLE
00:12.0 USB controller cannot be enabled

### ISSUE THREAD

**Issue by pietrushnic** [pcengines/coreboot#171]
This probably some porting issue

**Comment by miczyg1** [comment]
@pietrushnic probably not. Have a look here:
https://github.com/pcengines/coreboot/blob/775da85a8fb1ec8829fadd7c171726df681e77c5/src/mainboard/pcengines/apu2/BiosCallOuts.c#L95
EHCI0 is permanently disabled on apu2, because the pin header is not present on this board.

**Comment by miczyg1** [comment]
https://gitlab.com/3mdeb/rte/pcengines-rte/merge_requests/35
