### ISSUE TITLE
Legacy DMI table update

### ISSUE THREAD

**Issue by artur-rs** [pcengines/coreboot#210]
After test improvements for APUs mainline, legacy should contain coreboot release date with slashes - it will help with future validation. Mainline issue: https://github.com/pcengines/apu2-documentation/issues/117

**Comment by pietrushnic** [comment]
@miczyg1 this is a very simple fix, but I assume we have to schedule it for next iteration `v4.0.21` ?

**Comment by miczyg1** [comment]
https://github.com/pcengines/coreboot/pull/213
