### ISSUE TITLE
BIOS apu2_v4.11.0.5.rom "hides" 2nd WiFi card

### ISSUE THREAD

**Issue by alainlamar** [pcengines/coreboot#396]
Hi there,

I use an APU2C4 with 2x WLE600VX WiFi cards on Debian Buster (VyOS v1.3). While running on BIOS `apu2_v4.9.0.6.rom`, both cards are visible using 'lspci' and within /sys:

```
vyos@apu2c4:~$ ls -l /sys/class/ieee80211/
total 0
lrwxrwxrwx 1 root root 0 Apr 11 20:07 phy0 -> ../../devices/pci0000:00/0000:00:02.1/0000:01:00.0/ieee80211/phy0
lrwxrwxrwx 1 root root 0 Apr 11 20:07 phy1 -> ../../devices/pci0000:00/0000:00:02.5/0000:05:00.0/ieee80211/phy1
vyos@apu2c4:~$
```

After patching the BIOS to `apu2_v4.11.0.5.rom`, only one of the two cards is detected:

```
vyos@apu2c4:~$ ls -l /sys/class/ieee80211/
total 0
lrwxrwxrwx 1 root root 0 Apr 11 20:07 phy0 -> ../../devices/pci0000:00/0000:00:02.5/0000:04:00.0/ieee80211/phy0
vyos@apu2c4:~$
```

Also, the dmesg output lists only that one device, no sign whatsoever of the other device. I played around with a few BIOS settings that weren't there in the old BIOS, but none of them got me the second adapter back.

After flashing back to the old BIOS, both cards were present again and worked as intended.

Is there a bug in the new BIOS or do I miss some setting?

Best regards and Happy Easter - despite the circumstances...
-- Alain

Copy of PC-Engines forum post: [BIOS apu2_v4.11.0.5.rom "hides" 2nd WiFi card](http://www.pcengines.info/forums/?page=post&id=70A9F7A1-8440-4AC0-80E2-B24A438092D8&fid=DF5ACB70-99C4-4C61-AFA6-4C0E0DB05B2A)

**Comment by miczyg1** [comment]
Your issue kind of duplicates the https://github.com/pcengines/coreboot/issues/388
You may track the issue there.
