### ISSUE TITLE
Wrong serial number in dmidecode on APU1 is back

### ISSUE THREAD

**Issue by pcenginetest** [pcengines/coreboot#436]
coreboot image : apu1_v4.12.0.3.rom

i can't re open the Ticket #402 ?

**Comment by miczyg1** [comment]
Yes, please. Could you additionally paste the bad output and expected serial number?

**Comment by pcenginetest** [comment]
Handle 0x0002, DMI type 2, 14 bytes
Base Board Information
	Manufacturer: PC Engines
	Product Name: apu1
	Version: 1.0
	Serial Number: -64
	Asset Tag: Not Specified
	Features: None
	Location In Chassis: Not Specified
	Chassis Handle: 0x0003
	Type: Unknown

**Comment by zokl** [comment]
4.13.0.1 have the same issue.

**Comment by miczyg1** [comment]
The patch has been merged that fixes it: https://review.coreboot.org/c/coreboot/+/42512 
We will re-investigate the issue, since the test still fails.

**Comment by miczyg1** [comment]
Since v4.13.0.2 it is definitely fixed.
https://github.com/pcengines/coreboot/blob/release/CHANGELOG.md#v41302---2020-12-28

Also, our tests don't show errors and the serial number is calculated correctly from the MAC address. Closing
